# Root logger
rootLogger.level = INFO
rootLogger.appenderRef.console.ref = Console

# Console appender
appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} [ %-5level] %-25t: %replace{%logger}{com\.github\.dkw87\.chronostt\.}{}.%M() -> %msg%n

# Package logger
logger.chronostt.name = com.github.dkw87.chronostt
logger.chronostt.level = DEBUG
logger.chronostt.additivity = false
logger.chronostt.appenderRef.console.ref = Console